# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bcdd5d5bc88cd57a43521fc760004945ef4c4791e2e6f016b7bb6ddd2416776871192ab3c8f55246362c32deca80d4317358e20a74851dded3fd456be047def

test:
  secret_key_base: ec1e7014c9d4bc9b4e8eb74c52de976ee862b8b64feb74eaeab1b16ea6efce1dae81524031f4d704505b818693496b50d1d3a96772cada4c2463e4ea888e8eb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
